#! /bin/bash

TEST_FLAG=$1

docker build \
	-t kklipsch/reagled \
	--build-arg TEST_FLAG=$TEST_FLAG \
	--build-arg REAGLE_LOCAL_LOCATION=$REAGLE_LOCAL_LOCATION \
	--build-arg REAGLE_LOCAL_USER=$REAGLE_LOCAL_USER \
	--build-arg REAGLE_LOCAL_PASSWORD=$REAGLE_LOCAL_PASSWORD \
	--build-arg REAGLE_IMPROVED_FIRMWARE=$REAGLE_IMPROVED_FIRMWARE \
	--build-arg REAGLE_MODEL_ID_NAME=$REAGLE_MODEL_ID_NAME \
	--build-arg REAGLE_DEBUG_REQUEST=$REAGLE_DEBUG_REQUEST \
	--build-arg REAGLE_DEBUG_RESPONSE=$REAGLE_DEBUG_RESPONSE \
	--no-cache .
