#! /bin/bash

docker run \
	-e REAGLE_LOCAL_LOCATION=$REAGLE_LOCAL_LOCATION \
	-e REAGLE_LOCAL_USER=$REAGLE_LOCAL_USER \
	-e REAGLE_LOCAL_PASSWORD=$REAGLE_LOCAL_PASSWORD \
	-e REAGLE_IMPROVED_FIRMWARE=$REAGLE_IMPROVED_FIRMWARE \
	-e REAGLE_MODEL_ID_NAME=$REAGLE_MODEL_ID_NAME \
	-e REAGLE_DEBUG_REQUEST=$REAGLE_DEBUG_REQUEST \
	-e REAGLE_DEBUG_RESPONSE=$REAGLE_DEBUG_RESPONSE \
	-p 9000:9000 \
	kklipsch/reagled
